### PR TITLE
Decrease run time

### PR DESCRIPTION
**Pull request by joaander**
## Description

Decrease the run time of the examples. 
* Decrease system size
* Decrease run length accordingly
* Reduce fresnel image resolution and number of samples

On my linux box, they now run in 10 minutes. On Azure, they run in 20 minutes (compare to 5 hours previously).

Also:
* Run all examples on the CPU
* Adjust outputs to remove pointer addresses

With these changes, the notebook outputs are now as reproducible as they can be. The HOOMD trajectories and the fresnel renderings do not change when rerun on the same system. We may make use of this in the future and have the CI committing the notebook output.

The only changes in the diffs on rerunning (with the same binaries) are now:
* walltime/TPS output in the logging tutorial
* iopub exeuction timing in all cells

There is supposed to be a `record_timing` metadata key and/or nbconvert option to prevent `iopub` date/time information from changing the cell metadata every time the notebook is rerun. However, I was unable to get this option to have any effect.

## Checklist:
- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-examples/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-examples/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of authors](https://github.com/glotzerlab/hoomd-examples/blob/master/AUTHORS.md).

### CODE REVIEW

**Comment by bdice** [comment]
@joaander You might find this set of pre-commit hooks helpful as well:
https://github.com/glotzerlab/signac-examples/blob/a3d1729ea716cec2f8e51e950fcb6e0f14ef2775/.pre-commit-config.yaml
- strips metadata (iopub and more)
- replaces absolute paths with relative paths in the output cells (/home/joaander/.../project/notebooks/Test.ipynb becomes notebooks/Test.ipynb)
- Formats input cells with black/isort/pyupgrade

**Comment by joaander** [comment]
> @joaander You might find this set of pre-commit hooks helpful as well:
> https://github.com/glotzerlab/signac-examples/blob/a3d1729ea716cec2f8e51e950fcb6e0f14ef2775/.pre-commit-config.yaml
> 
> * strips metadata (iopub and more)
> * replaces absolute paths with repository-relative paths in the output cells (/home/joaander/.../project/notebooks/Test.ipynb becomes notebooks/Test.ipynb)
> * Formats input cells with black/isort/pyupgrade

If you think it would be useful, feel free to make a PR. We do need to preserve some metadata (nbsphinx hidden cells and a tag that allows the notebook to continue when a cell throws an excption).

**Comment by tommy-waltmann** [comment]
Does the current runtime of the notebooks ensure they aren't a bottleneck for CI now?

**Comment by joaander** [comment]
> Does the current runtime of the notebooks ensure they aren't a bottleneck for CI now?

Yes, the runtime reduction from 5 hours to 20 minutes is significant.

**Review by b-butler — APPROVED** [review]
The changes LGTM. Also the cut down in time is great!

**Comment by bdice** [comment]
I’ll pause on #22 until this is merged, to avoid burning tons of CI time.

**Review by tommy-waltmann — APPROVED** [review]

**Pull request merged**
