### PR TITLE
`HDF5Log` tutorial.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Switch from GSD with Null filter to HDF5 for introduction logging tutorial.

## Checklist:
- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-examples/blob/trunk/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-examples/blob/trunk/ContributorAgreement.md).
- [x] My name is on the [list of authors](https://github.com/glotzerlab/hoomd-examples/blob/trunk/AUTHORS.md).

### CODE REVIEW

**Comment by joaander** [comment]
Reviewers: Note that ReviewNB does not properly display SVG images. See the new images here:
* https://github.com/glotzerlab/hoomd-examples/blob/hdf5log/02-Logging/01-Logging-to-a-file.ipynb
* https://github.com/glotzerlab/hoomd-examples/blob/hdf5log/02-Logging/02-Saving-Array-Quantities.ipynb

**Review by tommy-waltmann — APPROVED** [review]
LGTM

**Comment by joaander** [comment]
@Charlottez112 I would appreciate your review.

**Review by Charlottez112 — APPROVED** [review]
Looks great. Very clear. Thank you!

**Pull request merged**
